# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-13 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationtime', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=20, null=True)),
                ('action', models.PositiveSmallIntegerField(choices=[(1, '新增'), (2, '删除'), (3, '修改'), (4, '登录'), (5, '退出'), (500, '其他')], null=True)),
                ('operationmodule', models.CharField(max_length=100)),
                ('operation', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_system-log', 'Can see available system log'), ('view_personal-log', 'Can see available personal log')),
            },
        ),
    ]
