# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatelog',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(1, '新增'), (2, '删除'), (3, '修改'), (4, '登录'), (5, '退出'), (6, '查看'), (500, '其他')], null=True),
        ),
    ]
