# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_auto_20180706_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigations',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='图片'),
        ),
    ]
