# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_auto_20180706_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaviourt',
            name='user_faviourt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户收藏'),
        ),
    ]
